name: Deploy infrastructure and release Node.js application

on:
  push:
    branches:
      - main # Deploy only when changes are pushed to the 'main' branch

jobs:
  infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy or update infrastructure
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ vars.NODEJS_RG }}
          template: ./devops/dev/main.dev.bicep
          parameters: ./devops/dev/main.dev.bicepparam
          failOnStdErr: false

  build:
    needs: infrastructure
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies, build, and test
        run: |
          cd neramExpressApp # Adjust this to your project directory
          npm install
          npm run build --if-present
          npm test --if-present

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ./neramExpressApp # Match the directory where your app resides

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: Dev
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Setup Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.DEVAPPNAME }}
          package: ./neramExpressApp # Match the artifact directory
