name: Deploy infrastructure and release Node.js application

on:
  push:
    branches:
      - main # Deploy only when changes are pushed to the 'main' branch

jobs:
  infrastructure:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    steps:
      - uses: actions/checkout@v3 # Checkout the repository code

      - name: Setup Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # Ensure AZURE_CREDENTIALS is added to GitHub Secrets

      - name: Deploy or update infrastructure
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ vars.NODEJS_RG }} # Use a GitHub variable or hard-code the resource group
          template: ./devops/dev/main.dev.bicep # Ensure the correct path to your Bicep file
          parameters: ./devops/dev/main.dev.bicepparam # Ensure the correct path to your parameters file
          failOnStdErr: false

  build:
    needs: infrastructure # Wait for the infrastructure job to complete
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # Checkout the repository code

      - name: Setup Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies, build, and test
        run: |
          cd neramtry # Adjust this directory path to match your project structure
          npm install
          npm run build --if-present
          npm test --if-present

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ./myExpressApp

  deploy:
    needs: build # Wait for the build job to complete
    runs-on: ubuntu-latest
    environment:
      name: Dev # Define the deployment environment
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Setup Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.DEVAPPNAME }} # Use a GitHub variable or hard-code the app name
          package: ./myExpressApp
