name: Deploy infrastructure and relase node js application
## Here is an example snippet which you can use to deploy your infrastructure to Azure

on:
  push:
    branches:
      - main # Change this to any other branch you wish to deploy to

jobs:
  infrastructure: # You can change this name to anything else you wish
    runs-on: ubuntu-latest # This could also be a windows machine e.g windows-latest

    steps:
      - uses: actions/checkout@v2 # This will obtain all the code for you in your repository

      - name: Setup Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # Ensure you create a AZURE_CREDENTIALS secret object in your Github secrets and variables

      - name: Deploy or update infrastructure
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }} # If you have multiple subscriptions this will switch to the correct subscription for you
          resourceGroupName: ${{ vars.NODEJS_RG }} # This doesn't have to be a variable, you could also hard code this, but ensure you create a variable if you use this approach
          template: ./devops/dev/main.dev.bicep # This is an assumed directory structure ensure you change to the correct directory as well as rename environment to uat or prod etc
          parameters: ./devops/dev/main.dev.bicepparam
          failOnStdErr: false
  build:
    needs: infrastructure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js  version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      
      - name: npm install, build, and test
        run: | 
          cd myExpressApp
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: ./myExpressApp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Dev'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: Setup Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.DEVAPPNAME }}
          package: .