name: Deploy infrastructure and release Node.js application

on:
  push:
    branches:
      - main

jobs:
  infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy or update infrastructure
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.NODEJS_RG }}
          template: ./devops/dev/main.dev.bicep
          parameters: ./devops/dev/main.dev.bicepparam
          failOnStdErr: false

  build:
    needs: infrastructure
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies, build, and test
        run: |
          cd neramExpressApp
          npm install
          npm run build --if-present
          npm test --if-present

      - name: Create deployment package
        run: |
          cd neramExpressApp
          zip -r ../neramExpressApp.zip ./*

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: neramExpressApp.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: Dev

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Debug downloaded files
        run: ls -R .

      - name: Setup Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: nodeJSExpressAppunique123
          package: ./neramExpressApp.zip
          slot-name: production
